del mode.dat
copy M1AK78.AUT mode.dat
sg4
del mode.dat
copy M1AK89.AUT mode.dat
sg4
del mode.dat
copy M1AL78.AUT mode.dat
sg4
del mode.dat
copy M1GC90.AUT mode.dat
sg4
del mode.dat
copy M1MK78.AUT mode.dat
sg4
del mode.dat
copy M1MK89.AUT mode.dat
sg4
del mode.dat
copy M1PX78.AUT mode.dat
sg4
del mode.dat
copy M1PX89.AUT mode.dat
sg4
del mode.dat
copy M1TB89.AUT mode.dat
sg4
del mode.dat
copy M1MD861.AUT mode.dat
sg4
del mode.dat
copy M1MD862.AUT mode.dat
sg4
del mode.dat
copy M1MT851.AUT mode.dat
sg4
del mode.dat
copy M1MT853.AUT mode.dat
sg4
